from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pickle

productive = [
    "Introduction to Algorithms: Dive into algorithm design and analysis, covering sorting, searching, and graph algorithms.",
    "Data Structures in Python: Learn about lists, stacks, queues, and trees, and how to implement them in Python.",
    "Operating Systems Concepts: Explore process management, memory management, and file systems in modern operating systems.",
    "Database Management Systems: Understand relational databases, SQL queries, normalization, and transaction management.",
    "Computer Networks: Study the OSI model, TCP/IP protocols, and network security fundamentals.",
    "Artificial Intelligence Basics: Get introduced to AI concepts, including machine learning, neural networks, and natural language processing.",
    "Software Engineering Principles: Learn about software development life cycles, agile methodologies, and project management.",
    "Web Development: Understand HTML, CSS, JavaScript, and frameworks like React and Angular for building dynamic websites.",
    "Cybersecurity Fundamentals: Explore topics like encryption, authentication, and common security threats.",
    "Cloud Computing: Learn about cloud service models (IaaS, PaaS, SaaS), deployment models, and cloud providers like AWS and Azure.",
    "Discrete Mathematics: Study logic, set theory, combinatorics, graph theory, and their applications in computer science.",
    "Computer Architecture: Understand the structure and behavior of computer systems, including CPUs, memory, and input/output devices.",
    "Programming Languages: Explore different programming paradigms and languages such as Python, Java, C++, and JavaScript.",
    "Compiler Design: Learn how compilers translate high-level code into machine code, including lexical analysis and parsing.",
    "Human-Computer Interaction: Study the design and evaluation of user interfaces and user experience.",
    "Mobile App Development: Learn to build applications for Android and iOS platforms using tools like Flutter and React Native.",
    "Machine Learning: Dive into supervised and unsupervised learning, neural networks, and deep learning techniques.",
    "Data Science: Explore data analysis, visualization, and statistical modeling using tools like Pandas and Matplotlib.",
    "Big Data Technologies: Understand Hadoop, Spark, and NoSQL databases for handling large-scale data processing.",
    "DevOps Practices: Learn about continuous integration, continuous deployment, and infrastructure as code.",
    "Version Control Systems: Master Git and GitHub for source code management and collaboration.",
    "Agile Methodologies: Study Scrum, Kanban, and other agile frameworks for software development.",
    "Software Testing: Learn about unit testing, integration testing, and test-driven development.",
    "Computer Graphics: Explore rendering, modeling, and animation techniques using OpenGL and DirectX.",
    "Game Development: Understand game engines, physics simulation, and graphics for creating interactive games.",
    "Natural Language Processing: Study text processing, sentiment analysis, and language modeling.",
    "Robotics: Learn about sensors, actuators, and control systems in robotic applications.",
    "Quantum Computing: Explore the principles of quantum mechanics applied to computation.",
    "Ethical Hacking: Understand penetration testing, vulnerability assessment, and security auditing.",
    "Blockchain Technology: Learn about decentralized systems, smart contracts, and cryptocurrencies.",
    "Internet of Things (IoT): Study connected devices, sensors, and data communication protocols.",
    "Augmented Reality (AR): Explore AR development using tools like ARKit and ARCore.",
    "Virtual Reality (VR): Learn about VR environments, hardware, and application development.",
    "Parallel Computing: Understand parallel algorithms, multi-threading, and distributed systems.",
    "Embedded Systems: Study microcontrollers, real-time operating systems, and hardware interfacing.",
    "Digital Signal Processing: Learn about signal analysis, filtering, and transformation techniques.",
    "Information Retrieval: Explore search engines, indexing, and ranking algorithms.",
    "Computer Vision: Study image processing, object detection, and facial recognition.",
    "Bioinformatics: Learn about computational biology, genome analysis, and protein structure prediction.",
    "E-commerce Systems: Understand online transaction processing, payment gateways, and security.",
    "Software Project Management: Study project planning, risk management, and resource allocation.",
    "IT Service Management: Learn about ITIL frameworks and service delivery models.",
    "Data Warehousing: Explore data integration, ETL processes, and OLAP systems.",
    "Business Intelligence: Understand data analytics, dashboards, and decision support systems.",
    "Artificial Neural Networks: Dive into perceptrons, backpropagation, and deep learning architectures.",
    "Reinforcement Learning: Study agents, environments, and reward-based learning models.",
    "Computer Forensics: Learn about digital evidence collection, analysis, and legal considerations.",
    "Cryptography: Understand symmetric and asymmetric encryption, hashing, and digital signatures.",
    "Software Architecture: Study design patterns, architectural styles, and system scalability.",
    "Cloud Security: Learn about securing cloud infrastructures and compliance standards.",
    "Data Privacy: Understand regulations like GDPR and techniques for data anonymization.",
    "IT Governance: Study frameworks like COBIT for aligning IT with business goals.",
    "Network Administration: Learn about configuring routers, switches, and network troubleshooting.",
    "System Administration: Understand operating system management, scripting, and automation.",
    "Technical Writing: Learn to document software requirements, user manuals, and API guides.",
    "User Experience (UX) Design: Study user research, wireframing, and usability testing.",
    "Digital Marketing: Explore SEO, SEM, and analytics tools for online marketing strategies.",
    "Entrepreneurship in Tech: Learn about startup development, funding, and product-market fit.",
    "Data Visualization: Understand tools like Tableau and D3.js for presenting data insights.",
    "Scientific Computing: Study numerical methods and simulations in scientific research.",
    "High-Performance Computing: Learn about supercomputers and parallel processing techniques.",
    "Software Localization: Understand adapting software for different languages and regions.",
    "Accessibility in Tech: Study designing inclusive technologies for users with disabilities.",
    "IT Compliance: Learn about standards like ISO 27001 and regulatory compliance.",
    "Digital Transformation: Understand integrating digital technology into business processes.",
    "Edge Computing: Explore computing at the edge of networks for real-time data processing.",
    "5G Technology: Learn about next-generation wireless communication and its applications.",
    "Smart Cities: Study the integration of technology in urban planning and services.",
    "Autonomous Vehicles: Understand the technology behind self-driving cars and navigation systems.",
    "Wearable Technology: Explore devices like smartwatches and fitness trackers.",
    "Digital Twins: Learn about virtual replicas of physical systems for simulation and analysis.",
    "Green Computing: Study energy-efficient computing and sustainable IT practices.",
    "Tech Policy and Law: Understand the legal aspects of technology and intellectual property.",
    "Digital Ethics: Explore the ethical implications of technology in society.",
    "Tech Entrepreneurship: Learn about building and scaling tech startups.",
    "Innovation Management: Study managing innovation processes within organizations.",
    "Product Management: Understand product lifecycle, roadmapping, and stakeholder communication.",
    "Technical Sales: Learn about selling complex technical products and solutions.",
    "Customer Relationship Management (CRM): Study systems for managing customer interactions.",
    "Enterprise Resource Planning (ERP): Understand integrated management of business processes.",
    "Supply Chain Management: Learn about logistics, procurement, and inventory management.",
    "Financial Technology (FinTech): Explore technology in financial services and banking.",
    "Health Informatics: Study the application of IT in healthcare settings.",
    "Educational Technology: Learn about digital tools and platforms in education.",
    "Legal Technology (LegalTech): Understand technology solutions in the legal industry.",
    "Agricultural Technology (AgriTech): Explore innovations in farming and food production.",
    "Environmental Technology: Study technologies aimed at environmental protection.",
    "Space Technology: Learn about satellite systems and space exploration technologies.",
    "Defense Technology: Understand technology applications in national defense.",
    "Art and Technology: Explore the intersection of creative arts and digital technology.",
    "Music Technology: Study digital audio workstations and sound engineering.",
    "Film and Video Technology: Learn about video editing, CGI, and post-production.",
    "Photography Technology: Understand digital imaging and photo editing software.",
    "Publishing Technology: Explore digital publishing platforms and e-books.",
    "Retail Technology: Study point-of-sale systems and e-commerce platforms.",
    "Hospitality Technology: Learn about hotel management systems and booking platforms.",
    "Transportation Technology: Understand logistics software and fleet management.",
    "Manufacturing Technology: Explore automation and industrial control systems.",
    "Construction Technology: Study building information modeling and project management tools.",
    "Real Estate Technology (PropTech): Learn about digital solutions in real estate.",
    "Energy Technology: Understand smart grids and renewable energy systems.",
    "Mining Technology: Explore automation and safety systems in mining operations.",
    "Oil and Gas Technology: Study exploration and drilling technologies.",
    "Telecommunications Technology: Learn about network infrastructure and communication protocols.",
    "Media and Entertainment Technology: Understand streaming platforms and content delivery networks.",
    "Sports Technology: Explore performance analytics and wearable devices in sports.",
    "Fashion Technology: Study digital design tools and e-commerce in fashion.",
    "Food Technology: Learn about food processing and safety technologies.",
    "Beverage Technology: Understand brewing and bottling technologies.",
    "Packaging Technology: Explore materials and machinery in packaging.",
    "Printing Technology: Study digital printing and 3D printing technologies.",
    "Textile Technology: Learn about fabric production and smart textiles.",
    "Automotive Technology: Understand vehicle systems and diagnostics.",
    "Aerospace Technology: Explore aircraft design and avionics systems.",
    "Marine Technology: Study shipbuilding and navigation systems.",
    "Railway Technology: Learn about train control systems and infrastructure.",
    "Logistics Technology: Understand supply chain optimization and tracking systems.",
    "Public Safety Technology: Explore emergency response systems and surveillance.",
    "Smart Home Technology: Study home automation and IoT devices.",
    "Assistive Technology: Learn about devices aiding individuals with disabilities.",
    "Gaming Technology: Understand game engines and virtual reality systems.",
    "Esports Technology: Explore streaming platforms and competitive gaming infrastructure.",
    "Social Media Technology: Study platform algorithms and user engagement strategies.",
    "Search Engine Technology: Learn about indexing, ranking, and search algorithms.",
    "Advertising Technology (AdTech): Understand programmatic advertising and data analytics.",
    "Marketing Technology (MarTech): Explore tools for campaign management and customer segmentation.",
    "Human Resources Technology (HRTech): Study recruitment platforms and employee management systems.",
    "Financial Services Technology: Learn about online banking and investment platforms.",
    "Insurance Technology (InsurTech): Understand digital solutions in the insurance industry.",
    "Legal Services Technology: Explore case management and legal research tools.",
    "Accounting Technology: Study software for financial reporting and compliance.",
    "Consulting Technology: Learn about tools and methodologies"]
 
unproductive = [
    "Watching cat videos on YouTube for hours.",
    "Scrolling endlessly through social media feeds.",
    "Binge-watching reality TV shows.",
    "Reading celebrity gossip articles.",
    "Playing mobile games with no educational value.",
    "Participating in online flame wars.",
    "Watching prank videos.",
    "Engaging in clickbait quizzes.",
    "Browsing meme pages.",
    "Watching unboxing videos.",
    "Following drama on influencer channels.",
    "Reading conspiracy theory forums.",
    "Watching reaction videos to other reaction videos.",
    "Participating in meaningless online polls.",
    "Viewing compilations of fails.",
    "Reading horoscope predictions.",
    "Watching ASMR videos with no relaxation benefit.",
    "Engaging in online trolling.",
    "Watching endless TikTok dances.",
    "Reading about celebrity breakups.",
    "Participating in chain emails or messages.",
    "Watching videos of people eating large amounts of food.",
    "Engaging in online gambling.",
    "Browsing through endless product reviews without intent to buy.",
    "Watching soap operas.",
    "Reading about alien abductions.",
    "Participating in online petitions with no real impact.",
    "Watching videos of people popping pimples.",
    "Engaging in online dating apps without serious intent.",
    "Watching home shopping networks.",
    "Reading about royal family gossip.",
    "Watching videos of people playing with slime.",
    "Engaging in online debates about fictional characters.",
    "Watching videos of people opening mystery boxes.",
    "Reading about the latest diet fads.",
    "Watching videos of people reacting to food.",
    "Engaging in online forums about flat earth theories.",
    "Watching videos of people trying on clothes.",
    "Reading about the latest celebrity fashion trends.",
    "Watching videos of people doing makeup tutorials.",
    "Engaging in online forums about time travel.",
    "Watching videos of people building things with LEGO.",
    "Reading about the latest tech rumors.",
    "Watching videos of people playing with toys.",
    "Engaging in online forums about ghost sightings.",
    "Watching videos of people doing yoga challenges.",
    "Reading about the latest movie spoilers.",
    "Watching videos of people doing extreme sports.",
    "Engaging in online forums about mythical creatures.",
    "Watching videos of people doing magic tricks.",
    "Reading about the latest video game cheats.",
    "Watching videos of people doing parkour.",
    "Engaging in online forums about ancient aliens.",
    "Watching videos of people doing cooking challenges.",
    "Reading about the latest fashion trends.",
    "Watching videos of people doing nail art.",
    "Engaging in online forums about conspiracy theories.",
    "Watching videos of people doing hair tutorials.",
    "Reading about the latest celebrity scandals.",
    "Watching videos of people doing prank calls.",
    "Engaging in online forums about UFO sightings.",
    "Watching videos of people doing dance challenges.",
    "Reading about the latest music gossip.",
    "Watching videos of people doing makeup transformations.",
    "Engaging in online forums about supernatural events.",
    "Watching videos of people doing DIY crafts.",
    "Reading about the latest sports rumors.",
    "Watching videos of people doing fitness challenges.",
    "Engaging in online forums about end-of-the-world predictions.",
    "Watching videos of people doing reaction videos.",
    "Reading about the latest TV show theories.",
    "Watching videos of people doing unboxing videos.",
    "Engaging in online forums about mythical lands.",
    "Watching videos of people doing life hacks.",
    "Reading about the latest internet challenges.",
    "Watching videos of people doing ASMR eating.",
    "Engaging in online forums about lost civilizations.",
    "Watching videos of people doing product reviews.",
    "Reading about the latest celebrity tweets.",
    "Watching videos of people doing room tours.",
    "Engaging in online forums about paranormal activities.",
    "Watching videos of people doing travel vlogs.",
    "Reading about the latest fashion faux pas.",
    "Watching videos of people doing tech unboxings.",
    "Engaging in online forums about ancient prophecies.",
    "Watching videos of people doing daily routines.",
    "Reading about the latest movie Easter eggs.",
    "Watching videos of people doing cleaning routines.",
    "Engaging in online forums about secret societies.",
    "Watching videos of people doing shopping hauls.",
    "Reading about the latest music video interpretations.",
    "Watching videos of people doing pet care routines.",
    "Engaging in online forums about hidden messages in media.",
    "Watching videos of people doing morning routines.",
    "Reading about the latest celebrity diets.",
    "Watching videos of people doing skincare routines.",
    "Engaging in online forums about numerology.",
    "Watching videos of people doing nighttime routines.",
    "Reading about the latest viral memes.",
    "Watching videos of people doing productivity hacks.",
    "Engaging in online forums about astrology.",
    "Watching videos of people doing study routines.",
    "Reading about the latest internet controversies.",
    "Watching videos of people doing journaling techniques.",
    "Engaging in online forums about dream interpretations.",
    "Watching videos of people doing bullet journaling.",
    "Reading about the latest social media trends.",
    "Watching videos of people doing digital planning.",
    "Engaging in online forums about past life experiences.",
    "Watching videos of people doing stationery hauls.",
    "Reading about the latest influencer collaborations.",
    "Watching videos of people doing desk setups.",
    "Engaging in online forums about psychic abilities.",
    "Watching videos of people doing room makeovers.",
    "Reading about the latest tech gadgets.",
    "Watching videos of people doing aesthetic compilations.",
    "Engaging in online forums about spiritual awakenings.",
    "Watching videos of people doing lifestyle vlogs.",
    "Reading about the latest online challenges.",
    "Watching videos of people doing Q&A sessions.",
    "Engaging in online forums about manifestation techniques.",
    "Watching videos of people doing storytime videos.",
    "Reading about the latest YouTube drama.",
    "Watching videos of people doing mukbangs.",
    "Engaging in online forums about law of attraction.",
    "Watching videos of people doing daily vlogs.",
    "Reading about the latest TikTok trends.",
    "Watching videos of people doing challenges.",
    "Engaging in online forums about energy healing.",
    "Watching videos of people doing tag videos.",
    "Reading about the latest influencer feuds.",
    "Watching videos of people doing reaction videos.",
    "Engaging in online forums about crystal healing.",
    "Watching videos of people doing compilation videos.",
    "Reading about the latest social media algorithms.",
    "Watching videos of people doing parody videos.",
    "Engaging in online forums about aura readings.",
    "Watching videos of people doing skits.",
    "Reading about the latest meme formats.",
    "Watching videos of people doing comedy sketches.",
    "Engaging in online forums about chakra balancing.",
    "Watching videos of people doing lip-syncing.",
    "Reading about the latest viral challenges.",
    "Watching videos of people doing dance covers.",
    "Engaging in online forums about tarot readings.",
    "Watching videos of people doing prank wars.",
    "Reading about the latest internet slang.",
    "Watching videos of people doing social experiments.",
    "Engaging in online forums about past life regression.",
    "Watching videos of people doing public interviews.",
    "Reading about the latest influencer scandals.",
    "Watching videos of people doing reaction compilations.",
    "Engaging in online forums about dream analysis.",
    "Watching videos of people doing parody songs.",
    "Reading about the latest viral videos.",
    "Watching videos of people doing TikTok compilations.",
    "Engaging in online forums about spiritual journeys.",
    "Watching videos of people doing meme reviews.",
    "Reading about the latest YouTube trends.",
    "Watching videos of people doing challenge compilations.",
    "Engaging in online forums about energy vibrations.",
    "Watching videos of people doing reaction mashups.",
    "Reading about the latest social media updates.",
    "Watching videos of people doing prank compilations.",
    "Engaging in online forums about spiritual enlightenment.",
    "Watching videos of people doing dance challenges.",
    "Reading about the latest influencer marketing strategies.",
    "Watching videos of people doing lip-sync battles.",
    "Engaging in online forums about meditation techniques.",
    "Watching videos of people doing reaction challenges.",
    "Reading about the latest viral content.",
    "Watching videos of people doing comedy challenges.",
    "Engaging in online forums about mindfulness practices.",
    "Watching videos of people doing parody challenges.",
    "Reading about the latest internet phenomena.",
    "Watching videos of people doing social media experiments.",
    "Engaging in online forums about self-discovery journeys.",
    "Watching videos of people doing reaction videos to trends.",
    "Reading about the latest online sensations.",
    "Watching videos of people doing challenge reactions.",
    "Engaging in online forums about personal growth stories.",
    "Watching videos of people doing viral trend reactions.",
    "Reading about the latest digital content trends.",
    "Watching videos of people doing meme challenges.",
    "Engaging in online forums about life purpose discussions.",
    "Watching videos of people doing internet trend reactions.",
    "Reading about the latest online content creators.",
    "Watching videos of people doing reaction videos to memes.",
    "Engaging in online forums about self-improvement techniques.",
    "Watching videos of people doing challenge videos.",
    "Reading about the latest social media influencers.",
    "Watching videos of people doing reaction videos to challenges.",
    "Engaging in online forums about personal development journeys.",
    "Watching videos of people doing viral challenge reactions.",
    "Reading about the latest online content trends.",
    "Watching videos of people doing meme reactions.",
    "Engaging in online forums about self-help strategies.",
    "Watching videos of people doing internet challenge reactions.",
    "Reading about the latest digital media trends.",
    "Watching videos of people doing reaction videos to viral content.",
    "Engaging in online forums about self-awareness practices.",
    "Watching videos of people doing challenge reactions.",
    "Reading about the latest online entertainment trends.",
    "Watching videos of people doing reaction videos to internet trends.",
    "Engaging in online forums about personal growth techniques.",
    "Watching videos of people doing viral trend reactions.",
    "Reading about the latest social media content.",
    "Watching videos of people doing meme reactions.",
    "Engaging in online forums about self-improvement journeys.",
    "Watching videos of people doing internet trend reactions.",
    "Reading about the latest digital content creators.",
    "Watching videos of people doing reaction videos to memes.",
    "Engaging in online forums about self-help practices.",
    "Watching videos of people doing challenge videos.",
    "Reading about the latest social media influencers.",
    "Watching videos of people doing reaction videos to"]

texts = productive + unproductive
labels = [1] * len(productive) + [0] * len(unproductive)

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(texts)

model = LogisticRegression()

X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2)
model.fit(X_train, y_train)
predictions = model.predict(X_test)

new_page = ["watch videos"]
X_new = vectorizer.transform(new_page)
print(model.predict(X_new)) 

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)